# Generated by Django 5.1.3 on 2024-11-06 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="auth_app.user"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administration.staff",
            ),
        ),
    ]
