# Generated by Django 5.1.3 on 2024-11-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0002_initial"),
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_app.user",
            ),
        ),
    ]
