# Generated by Django 5.1.3 on 2024-11-19 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_rename_stuff_number_staff_staff_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="office",
            name="building_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="office_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
