# Generated by Django 5.1.3 on 2024-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0005_staff_added_date_alter_office_building_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(default="umams1200@gmail.com", max_length=254),
        ),
    ]
